# Generated by Django 3.1.6 on 2021-04-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('headline', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('content', models.TextField()),
            ],
        ),
    ]
